# Generated by Django 3.0.8 on 2020-07-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('price', models.FloatField(verbose_name='价格')),
                ('original', models.CharField(max_length=20, verbose_name='出处')),
                ('image', models.CharField(max_length=75, verbose_name='路径')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('账号', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('密码', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
    ]
